
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: rog-exercise
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

volumes:
  mongo-data:
